import { motion, useInView } from 'framer-motion';
import { useRef } from 'react';
import { Star, Quote, Sparkles } from 'lucide-react';

const testimonials = [
  {
    name: 'Michael Chen',
    role: 'CEO, TechStart Inc.',
    image: '/testimonial-1.jpg',
    content: 'Universal Doc has completely transformed how we create business proposals. What used to take days now takes minutes. The AI understands exactly what we need.',
    rating: 5,
  },
  {
    name: 'Sarah Kim',
    role: 'Legal Director, Global Corp',
    image: '/testimonial-2.jpg',
    content: 'As a legal professional, I was skeptical at first. But the accuracy and professionalism of the legal documents generated is remarkable. A game-changer for our firm.',
    rating: 5,
  },
  {
    name: 'David Martinez',
    role: 'Marketing Director, Creative Agency',
    image: '/testimonial-3.jpg',
    content: 'The marketing copy generated by Universal Doc has increased our conversion rates by 40%. It\'s like having a copywriter available 24/7.',
    rating: 5,
  },
];

const trustedCompanies = ['Google', 'Microsoft', 'Amazon', 'Meta', 'Apple'];

export function TestimonialsSection() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-50px' });

  return (
    <section id="testimonials" className="py-16 sm:py-20 lg:py-32 relative overflow-hidden bg-background">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-muted/30 to-background" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        {/* Section Header */}
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          className="text-center mb-10 sm:mb-16"
        >
          <span className="inline-flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1.5 sm:py-2 rounded-full bg-primary/10 text-primary text-xs sm:text-sm font-medium mb-3 sm:mb-4">
            <Sparkles className="w-3 h-3 sm:w-4 sm:h-4" />
            Customer Stories
          </span>
          <h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold mb-3 sm:mb-4 text-foreground">
            Loved by{' '}
            <span className="bg-gradient-to-r from-primary to-orange-400 bg-clip-text text-transparent">
              10,000+ Users
            </span>
          </h2>
          <p className="text-sm sm:text-base lg:text-lg text-muted-foreground max-w-2xl mx-auto px-2 sm:px-0">
            See what professionals around the world are saying about Universal Document Creator.
          </p>
        </motion.div>

        {/* Testimonials Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6">
          {testimonials.map((testimonial, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: index * 0.15 }}
              whileHover={{ y: -5 }}
              className="group"
            >
              <div className="relative p-5 sm:p-6 lg:p-8 rounded-xl sm:rounded-2xl bg-card border border-border hover:border-primary/30 transition-all duration-300 hover:shadow-xl">
                {/* Quote Icon */}
                <div className="absolute -top-3 -left-2 sm:-top-4 sm:-left-2 w-8 h-8 sm:w-10 sm:h-10 rounded-full bg-primary flex items-center justify-center">
                  <Quote className="w-4 h-4 sm:w-5 sm:h-5 text-white" />
                </div>

                {/* Rating */}
                <div className="flex gap-1 mb-3 sm:mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-3.5 h-3.5 sm:w-4 sm:h-4 fill-amber-400 text-amber-400" />
                  ))}
                </div>

                {/* Content */}
                <p className="text-sm sm:text-base text-muted-foreground mb-4 sm:mb-6 leading-relaxed">
                  &quot;{testimonial.content}&quot;
                </p>

                {/* Author */}
                <div className="flex items-center gap-2 sm:gap-3">
                  <img
                    src={testimonial.image}
                    alt={testimonial.name}
                    className="w-10 h-10 sm:w-12 sm:h-12 rounded-full object-cover ring-2 ring-primary/20"
                  />
                  <div>
                    <h4 className="font-semibold text-sm sm:text-base text-foreground">{testimonial.name}</h4>
                    <p className="text-xs sm:text-sm text-muted-foreground">{testimonial.role}</p>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Trust Badges */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.5 }}
          className="mt-10 sm:mt-16 text-center"
        >
          <p className="text-xs sm:text-sm text-muted-foreground mb-3 sm:mb-4">Trusted by teams at</p>
          <div className="flex flex-wrap justify-center items-center gap-4 sm:gap-8 opacity-50">
            {trustedCompanies.map((company) => (
              <span key={company} className="text-base sm:text-lg lg:text-xl font-bold text-muted-foreground">
                {company}
              </span>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  );
}
